--HOW TO CALL A TABKE IF 2 DIFFERENT DATABASE HAVE THE SAME TABLE NAME(TABLE DATA IS DIFF)?
--You cannot directly call tables from two different PostgreSQL databases. 
--You must connect to each database separately, or use postgres_fdw to link them.
SELECT * FROM CUSTOMER;

--Q1. What is the total revenue generated by male vs female customers?

SELECT GENDER, SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY GENDER
ORDER BY TOTAL_REVENUE DESC;

-- Q2. Which customer used a discount but still spent more than the average purchase amount?

SELECT CUSTOMER_ID , PURCHASE_AMOUNT
FROM CUSTOMER
WHERE DISCOUNT_APPLIED ='Yes'
AND PURCHASE_AMOUNT > (SELECT AVG(PURCHASE_AMOUNT) FROM CUSTOMER);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT ITEM_PURCHASED , ROUND(AVG(REVIEW_RATING::NUMERIC),3) AS AVERAGE_RATING
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY AVERAGE_RATING DESC 
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.

SELECT SHIPPING_TYPE, ROUND(AVG(PURCHASE_AMOUNT),5)
FROM CUSTOMER
WHERE SHIPPING_TYPE IN ('Standard','Express')
GROUP BY SHIPPING_TYPE;

-- Q5. Do subscribed customers spend more? 
-- Compare avg spend & total revenue btw subscribers & non-subscribers.

SELECT COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
SUBSCRIPTION_STATUS , 
ROUND(AVG(PURCHASE_AMOUNT),3) AS AVG_REVENUE , 
SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY SUBSCRIPTION_STATUS; 

--Q6. Which 5 products have the highest % of purchases with discounts applied?

SELECT ITEM_PURCHASED,
100*SUM(CASE WHEN DISCOUNT_APPLIED = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) AS PERCENTAGE_OF_PURCHASES
FROM CUSTOMER
GROUP BY ITEM_PURCHASED 
ORDER BY PERCENTAGE_OF_PURCHASES DESC
LIMIT 5;

SELECT ITEM_PURCHASED,
COUNT(CUSTOMER_ID) AS TOTAL_CUSTOMERS,
COUNT(*)  FILTER (where DISCOUNT_APPLIED = 'Yes') as CUSTOMERS_WITH_DISCOUNT,
ROUND(100*(COUNT(*)  FILTER (where DISCOUNT_APPLIED = 'Yes'))/COUNT(CUSTOMER_ID),3) AS PER_PUR_WITH_DISCOUNT
FROM CUSTOMER
GROUP BY ITEM_PURCHASED
ORDER BY PER_PUR_WITH_DISCOUNT DESC
LIMIT 5;

-- Q7. Segment customers into new , returning and loyal based on their total
-- number of previous purchases and show the count of each segment

-- Concept: Customer Segmentation -> categorizing customers 

-- Segmentation Definition (can be any)
-- let us say , purchase count = 1 -> new ; = >2&<10 -> returning ; >10 -> loyal
-- CTE METHOD IS USED HERE

WITH CUSTOMER_TYPE AS (
SELECT CUSTOMER_ID , PREVIOUS_PURCHASES,
CASE 
WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'Returning'
WHEN PREVIOUS_PURCHASES>10 THEN 'Loyal'
END 
AS CUSTOMER_SEGMENT
FROM CUSTOMER
)
SELECT CUSTOMER_SEGMENT , COUNT(*) AS "No of customers"
FROM CUSTOMER_TYPE
GROUP BY CUSTOMER_SEGMENT
ORDER BY "No of customers";

-- Q8. What are the top 3 most purchased products within each category?
-- ROW_NUMBER() ,RANK() , DENSE_RANK() CONCEPTS & WHEN TO USE WHEN?
-- learn this...***
SELECT  CATEGORY ,
ITEM_PURCHASED, 
COUNT(ITEM_PURCHASED) AS "NO OF ITEMS PURCHASED"
FROM CUSTOMER
GROUP BY CATEGORY , ITEM_PURCHASED
ORDER BY CATEGORY  ASC, "NO OF ITEMS PURCHASED" DESC;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT SUBSCRIPTION_STATUS,
COUNT(CUSTOMER_ID) AS REPEAT_BUYERS
FROM CUSTOMER
WHERE PREVIOUS_PURCHASES >5
GROUP BY SUBSCRIPTION_STATUS;

-- Q10. What is the revenue contribution by age group?

SELECT AGE_GROUP , SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM CUSTOMER
GROUP BY AGE_GROUP
ORDER BY TOTAL_REVENUE DESC

